// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
@_spi(GoogleCloudInternal) public import GoogleLongRunning
@_spi(GoogleCloudInternal) public import GoogleGax

/// The IDS Service
///
/// @Snippet(path: "IDSQuickstart")
public final class IDSClient: Clients.IDSProtocol, Sendable {
  let inner: any Clients.IDSStub
  let pollingErrorPolicy: GoogleGax.PollingErrorPolicy
  let pollingBackoffPolicy: GoogleGax.BackoffPolicy

  /// Creates a new `IDSClient` instance.
  public init(_ options: GoogleGax.ClientOptions = .init()) throws {
    var inner: any Clients.IDSStub = try Clients.IDSTransport(options)
    inner = Clients.IDSRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.IDSLogging(inner, logger: logger)
    }
    self.inner = inner
    self.pollingErrorPolicy = options.pollingErrorPolicy
    self.pollingBackoffPolicy = options.pollingBackoffPolicy
  }

  /// Lists Endpoints in a given project and location.
  ///
  /// @Snippet(path: "IDS_ListEndpoints")
  public func listEndpoints(
    request: ListEndpointsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudIDSV1.ListEndpointsResponse {
    try await self.inner.listEndpoints(request: request, options: options)
  }

  /// Gets details of a single Endpoint.
  ///
  /// @Snippet(path: "IDS_GetEndpoint")
  public func getEndpoint(
    request: GetEndpointRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudIDSV1.Endpoint {
    try await self.inner.getEndpoint(request: request, options: options)
  }

  /// Creates a new Endpoint in a given project and location.
  ///
  /// @Snippet(path: "IDS_CreateEndpoint")
  public func createEndpoint(
    request: CreateEndpointRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.createEndpoint(request: request, options: options)
  }

  /// Creates a new Endpoint in a given project and location.
  ///
  /// @Snippet(path: "IDS_CreateEndpoint")
  public func createEndpointPollingUntilDone(
    request: CreateEndpointRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Endpoint> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws -> GoogleGax._PollableOperationImpl<Endpoint>.State
      in
      return try op._extractStatus(Endpoint.self)
    }
    let rawOp = try await self.createEndpoint(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Endpoint>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Deletes a single Endpoint.
  ///
  /// @Snippet(path: "IDS_DeleteEndpoint")
  public func deleteEndpoint(
    request: DeleteEndpointRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.deleteEndpoint(request: request, options: options)
  }

  /// Deletes a single Endpoint.
  ///
  /// @Snippet(path: "IDS_DeleteEndpoint")
  public func deleteEndpointPollingUntilDone(
    request: DeleteEndpointRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State
      in
      return try op._extractStatusEmpty()
    }
    let rawOp = try await self.deleteEndpoint(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "IDS_ListOperations")
  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    try await self.inner.listOperations(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "IDS_GetOperation")
  func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.getOperation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "IDS_DeleteOperation")
  public func deleteOperation(
    request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    try await self.inner.deleteOperation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "IDS_CancelOperation")
  public func cancelOperation(
    request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    try await self.inner.cancelOperation(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `IDSClient`.
  ///
  /// To mock `IDSClient` change your functions to receive
  /// `some IDSProtocol` or `any IDSProtocol`
  /// and pass a mock implementation in your tests.
  public protocol IDSProtocol: Sendable {
    /// See `IDSClient.createEndpoint`.
    func createEndpointPollingUntilDone(request: CreateEndpointRequest) async throws
      -> any GoogleGax.PollableOperation<Endpoint>

    /// See `IDSClient.createEndpoint`.
    func createEndpointPollingUntilDone(
      parent: Swift.String,
      endpoint: Endpoint?,
      endpointId: Swift.String,
    ) async throws -> any GoogleGax.PollableOperation<Endpoint>

    /// See `IDSClient.deleteEndpoint`.
    func deleteEndpointPollingUntilDone(request: DeleteEndpointRequest) async throws
      -> any GoogleGax.PollableOperation<Swift.Void>

    /// See `IDSClient.deleteEndpoint`.
    func deleteEndpointPollingUntilDone(
      name: Swift.String,
    ) async throws -> any GoogleGax.PollableOperation<Swift.Void>

    /// See `IDSClient.listEndpoints`.
    func listEndpoints(
      request: ListEndpointsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudIDSV1.ListEndpointsResponse

    /// See `IDSClient.getEndpoint`.
    func getEndpoint(
      request: GetEndpointRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudIDSV1.Endpoint

    /// See `IDSClient.createEndpoint`.
    func createEndpoint(
      request: CreateEndpointRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `IDSClient.createEndpoint`.
    func createEndpointPollingUntilDone(
      request: CreateEndpointRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Endpoint>

    /// See `IDSClient.deleteEndpoint`.
    func deleteEndpoint(
      request: DeleteEndpointRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `IDSClient.deleteEndpoint`.
    func deleteEndpointPollingUntilDone(
      request: DeleteEndpointRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Swift.Void>

    /// See `IDSClient.listOperations`.
    func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse

    /// See `IDSClient.deleteOperation`.
    func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
    ) async throws

    /// See `IDSClient.cancelOperation`.
    func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
    ) async throws
  }
}

// Default implementations
extension Clients.IDSProtocol {
  public func listEndpoints(request: ListEndpointsRequest) async throws
    -> GoogleCloudIDSV1.ListEndpointsResponse
  {
    try await self.listEndpoints(request: request, options: .init())
  }

  public func listEndpoints(
    request: ListEndpointsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudIDSV1.ListEndpointsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listEndpoints(
    byItem: ListEndpointsRequest
  ) -> any AsyncSequence<Endpoint, Swift.Error> {
    self.listEndpoints(byItem: byItem, options: .init())
  }

  /// Lists Endpoints in a given project and location.
  ///
  /// @Snippet(path: "IDS_ListEndpoints")
  public func listEndpoints(
    byItem: ListEndpointsRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<Endpoint, Swift.Error> {
    let listRpc = { (token: Swift.String) async throws -> GoogleCloudIDSV1.ListEndpointsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listEndpoints(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listEndpoints(
    parent: Swift.String,
  ) -> any AsyncSequence<Endpoint, Swift.Error> {
    let request = ListEndpointsRequest().with {
      $0.parent = parent
    }
    return self.listEndpoints(byItem: request)
  }

  public func getEndpoint(request: GetEndpointRequest) async throws -> GoogleCloudIDSV1.Endpoint {
    try await self.getEndpoint(request: request, options: .init())
  }

  public func getEndpoint(
    request: GetEndpointRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudIDSV1.Endpoint {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getEndpoint(
    name: Swift.String,
  ) async throws -> GoogleCloudIDSV1.Endpoint {
    let request = GetEndpointRequest().with {
      $0.name = name
    }
    return try await self.getEndpoint(request: request)
  }

  public func createEndpoint(request: CreateEndpointRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.createEndpoint(request: request, options: .init())
  }

  public func createEndpoint(
    request: CreateEndpointRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func createEndpointPollingUntilDone(request: CreateEndpointRequest) async throws
    -> any GoogleGax.PollableOperation<Endpoint>
  {
    try await self.createEndpointPollingUntilDone(request: request, options: .init())
  }

  public func createEndpointPollingUntilDone(
    request: CreateEndpointRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Endpoint> {
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Endpoint>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func createEndpointPollingUntilDone(
    parent: Swift.String,
    endpoint: Endpoint?,
    endpointId: Swift.String,
  ) async throws -> any GoogleGax.PollableOperation<Endpoint> {
    let request = CreateEndpointRequest().with {
      $0.parent = parent
      $0.endpoint = endpoint
      $0.endpointId = endpointId
    }
    return try await self.createEndpointPollingUntilDone(request: request)
  }

  public func deleteEndpoint(request: DeleteEndpointRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.deleteEndpoint(request: request, options: .init())
  }

  public func deleteEndpoint(
    request: DeleteEndpointRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteEndpointPollingUntilDone(request: DeleteEndpointRequest) async throws
    -> any GoogleGax.PollableOperation<Swift.Void>
  {
    try await self.deleteEndpointPollingUntilDone(request: request, options: .init())
  }

  public func deleteEndpointPollingUntilDone(
    request: DeleteEndpointRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func deleteEndpointPollingUntilDone(
    name: Swift.String,
  ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
    let request = DeleteEndpointRequest().with {
      $0.name = name
    }
    return try await self.deleteEndpointPollingUntilDone(request: request)
  }

  public func listOperations(request: GoogleLongRunning.ListOperationsRequest) async throws
    -> GoogleLongRunning.ListOperationsResponse
  {
    try await self.listOperations(request: request, options: .init())
  }

  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listOperations(
    byItem: GoogleLongRunning.ListOperationsRequest
  ) -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    self.listOperations(byItem: byItem, options: .init())
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "IDS_ListOperations")
  public func listOperations(
    byItem: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleLongRunning.ListOperationsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listOperations(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listOperations(
    name: Swift.String,
    filter: Swift.String,
  ) -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    let request = GoogleLongRunning.ListOperationsRequest().with {
      $0.name = name
      $0.filter = filter
    }
    return self.listOperations(byItem: request)
  }

  public func getOperation(request: GoogleLongRunning.GetOperationRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.getOperation(request: request, options: .init())
  }

  public func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getOperation(
    name: Swift.String,
  ) async throws -> GoogleLongRunning.Operation {
    let request = GoogleLongRunning.GetOperationRequest().with {
      $0.name = name
    }
    return try await self.getOperation(request: request)
  }

  public func deleteOperation(request: GoogleLongRunning.DeleteOperationRequest) async throws {
    try await self.deleteOperation(request: request, options: .init())
  }

  public func deleteOperation(
    request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteOperation(
    name: Swift.String,
  ) async throws {
    let request = GoogleLongRunning.DeleteOperationRequest().with {
      $0.name = name
    }
    try await self.deleteOperation(request: request)
  }

  public func cancelOperation(request: GoogleLongRunning.CancelOperationRequest) async throws {
    try await self.cancelOperation(request: request, options: .init())
  }

  public func cancelOperation(
    request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    throw GoogleGax.RequestError.unimplemented
  }

  public func cancelOperation(
    name: Swift.String,
  ) async throws {
    let request = GoogleLongRunning.CancelOperationRequest().with {
      $0.name = name
    }
    try await self.cancelOperation(request: request)
  }
}
