// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudWkt
import GoogleLongRunning
import GoogleRpc
import GoogleCloudGax

/// The IDS Service
///
/// @Snippet(path: "IDSQuickstart")
public class IDSClient: Clients.IDSProtocol {
  let inner: any Clients.IDSStub
  let pollingErrorPolicy: GoogleCloudGax.PollingErrorPolicy
  let pollingBackoffPolicy: GoogleCloudGax.BackoffPolicy

  /// Creates a new `IDSClient` instance.
  public init(_ options: GoogleCloudGax.ClientOptions = .init()) throws {
    var inner: any Clients.IDSStub = try Clients.IDSTransport(options)
    inner = Clients.IDSRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.IDSLogging(inner, logger: logger)
    }
    self.inner = inner
    self.pollingErrorPolicy = options.pollingErrorPolicy
    self.pollingBackoffPolicy = options.pollingBackoffPolicy
  }

  /// Lists Endpoints in a given project and location.
  ///
  /// @Snippet(path: "IDS_ListEndpoints")
  public func listEndpoints(
    request: ListEndpointsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudIDSV1.ListEndpointsResponse {
    try await self.inner.listEndpoints(request: request, options: options)
  }

  /// Lists Endpoints in a given project and location.
  ///
  /// @Snippet(path: "IDS_ListEndpoints")
  public func listEndpoints(
    byItem: ListEndpointsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Endpoint, Swift.Error> {
    let listRpc = { (token: Swift.String) async throws -> GoogleCloudIDSV1.ListEndpointsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listEndpoints(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Gets details of a single Endpoint.
  ///
  /// @Snippet(path: "IDS_GetEndpoint")
  public func getEndpoint(
    request: GetEndpointRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudIDSV1.Endpoint {
    try await self.inner.getEndpoint(request: request, options: options)
  }

  /// Creates a new Endpoint in a given project and location.
  ///
  /// @Snippet(path: "IDS_CreateEndpoint")
  public func createEndpoint(
    request: CreateEndpointRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.createEndpoint(request: request, options: options)
  }

  /// Creates a new Endpoint in a given project and location.
  ///
  /// @Snippet(path: "IDS_CreateEndpoint")
  public func createEndpoint(
    withPolling: CreateEndpointRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Endpoint> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<Endpoint>.State in
      guard op.done else {
        return .init(done: false, result: nil)
      }

      switch op.result {
      case .response(let anyValue):
        guard let anyValueUnwrapped = anyValue else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding(
                "Operation completed but response value was missing")))
        }
        let response = try Endpoint(fromAny: anyValueUnwrapped)
        return .init(done: true, result: .success(response))
      case .error(let status):
        guard let statusUnwrapped = status else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding("Operation completed but error value was missing")
            ))
        }
        let error = GoogleCloudGax.RequestError.service(
          GoogleCloudGax.ServiceError(
            code: GoogleRpc.Code(intValue: Int(statusUnwrapped.code)),
            message: statusUnwrapped.message))
        return .init(done: true, result: .failure(error))
      case .none:
        return .init(
          done: true,
          result: .failure(
            GoogleCloudGax.RequestError.binding("Operation completed but result was missing")))
      }
    }
    let rawOp = try await self.createEndpoint(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Endpoint>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Deletes a single Endpoint.
  ///
  /// @Snippet(path: "IDS_DeleteEndpoint")
  public func deleteEndpoint(
    request: DeleteEndpointRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.deleteEndpoint(request: request, options: options)
  }

  /// Deletes a single Endpoint.
  ///
  /// @Snippet(path: "IDS_DeleteEndpoint")
  public func deleteEndpoint(
    withPolling: DeleteEndpointRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Void> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws -> GoogleCloudGax._PollableOperationImpl<Void>.State
      in
      guard op.done else {
        return .init(done: false, result: nil)
      }

      switch op.result {
      case .response:
        return .init(done: true, result: .success(()))
      case .error(let status):
        guard let statusUnwrapped = status else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding("Operation completed but error value was missing")
            ))
        }
        let error = GoogleCloudGax.RequestError.service(
          GoogleCloudGax.ServiceError(
            code: GoogleRpc.Code(intValue: Int(statusUnwrapped.code)),
            message: statusUnwrapped.message))
        return .init(done: true, result: .failure(error))
      case .none:
        return .init(
          done: true,
          result: .failure(
            GoogleCloudGax.RequestError.binding("Operation completed but result was missing")))
      }
    }
    let rawOp = try await self.deleteEndpoint(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Void>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  ///
  /// @Snippet(path: "IDS_ListOperations")
  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    try await self.inner.listOperations(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  ///
  /// @Snippet(path: "IDS_ListOperations")
  public func listOperations(
    byItem: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleLongRunning.ListOperationsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listOperations(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  ///
  /// @Snippet(path: "IDS_GetOperation")
  func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.getOperation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  ///
  /// @Snippet(path: "IDS_DeleteOperation")
  public func deleteOperation(
    request: GoogleLongRunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    try await self.inner.deleteOperation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  ///
  /// @Snippet(path: "IDS_CancelOperation")
  public func cancelOperation(
    request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    try await self.inner.cancelOperation(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `IDSClient`.
  ///
  /// To mock `IDSClient` change your functions to receive
  /// `some IDSProtocol` or `any IDSProtocol`
  /// and pass a mock implementation in your tests.
  public protocol IDSProtocol {
    /// See `IDSClient.listEndpoints`.
    func listEndpoints(request: ListEndpointsRequest) async throws
      -> GoogleCloudIDSV1.ListEndpointsResponse

    /// See `IDSClient.listEndpoints`.
    func listEndpoints(
      byItem: ListEndpointsRequest
    ) throws -> any AsyncSequence<Endpoint, Swift.Error>

    /// See `IDSClient.listEndpoints`.
    func listEndpoints(
      parent: Swift.String,
    ) throws -> any AsyncSequence<Endpoint, Swift.Error>

    /// See `IDSClient.getEndpoint`.
    func getEndpoint(request: GetEndpointRequest) async throws -> GoogleCloudIDSV1.Endpoint

    /// See `IDSClient.getEndpoint`.
    func getEndpoint(
      name: Swift.String,
    ) async throws -> GoogleCloudIDSV1.Endpoint

    /// See `IDSClient.createEndpoint`.
    func createEndpoint(request: CreateEndpointRequest) async throws -> GoogleLongRunning.Operation

    /// See `IDSClient.createEndpoint`.
    func createEndpoint(withPolling: CreateEndpointRequest) async throws -> any GoogleCloudGax
      .PollableOperation<Endpoint>

    /// See `IDSClient.createEndpoint`.
    func createEndpoint(
      parent: Swift.String,
      endpoint: Endpoint?,
      endpointId: Swift.String,
    ) async throws -> any GoogleCloudGax.PollableOperation<Endpoint>

    /// See `IDSClient.deleteEndpoint`.
    func deleteEndpoint(request: DeleteEndpointRequest) async throws -> GoogleLongRunning.Operation

    /// See `IDSClient.deleteEndpoint`.
    func deleteEndpoint(withPolling: DeleteEndpointRequest) async throws -> any GoogleCloudGax
      .PollableOperation<Void>

    /// See `IDSClient.deleteEndpoint`.
    func deleteEndpoint(
      name: Swift.String,
    ) async throws -> any GoogleCloudGax.PollableOperation<Void>

    /// See `IDSClient.listOperations`.
    func listOperations(request: GoogleLongRunning.ListOperationsRequest) async throws
      -> GoogleLongRunning.ListOperationsResponse

    /// See `IDSClient.listOperations`.
    func listOperations(
      byItem: GoogleLongRunning.ListOperationsRequest
    ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error>

    /// See `IDSClient.listOperations`.
    func listOperations(
      name: Swift.String,
      filter: Swift.String,
    ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error>

    /// See `IDSClient.deleteOperation`.
    func deleteOperation(request: GoogleLongRunning.DeleteOperationRequest) async throws

    /// See `IDSClient.deleteOperation`.
    func deleteOperation(
      name: Swift.String,
    ) async throws

    /// See `IDSClient.cancelOperation`.
    func cancelOperation(request: GoogleLongRunning.CancelOperationRequest) async throws

    /// See `IDSClient.cancelOperation`.
    func cancelOperation(
      name: Swift.String,
    ) async throws

    /// See `IDSClient.listEndpoints`.
    func listEndpoints(
      request: ListEndpointsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudIDSV1.ListEndpointsResponse

    /// See `IDSClient.listEndpoints`.
    func listEndpoints(
      byItem: ListEndpointsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<Endpoint, Swift.Error>

    /// See `IDSClient.getEndpoint`.
    func getEndpoint(
      request: GetEndpointRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudIDSV1.Endpoint

    /// See `IDSClient.createEndpoint`.
    func createEndpoint(
      request: CreateEndpointRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `IDSClient.createEndpoint`.
    func createEndpoint(
      withPolling: CreateEndpointRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<Endpoint>

    /// See `IDSClient.deleteEndpoint`.
    func deleteEndpoint(
      request: DeleteEndpointRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `IDSClient.deleteEndpoint`.
    func deleteEndpoint(
      withPolling: DeleteEndpointRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<Void>

    /// See `IDSClient.listOperations`.
    func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse

    /// See `IDSClient.listOperations`.
    func listOperations(
      byItem: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error>

    /// See `IDSClient.deleteOperation`.
    func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    /// See `IDSClient.cancelOperation`.
    func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws
  }
}

// Default implementations
extension Clients.IDSProtocol {
  public func listEndpoints(request: ListEndpointsRequest) async throws
    -> GoogleCloudIDSV1.ListEndpointsResponse
  {
    try await self.listEndpoints(request: request, options: .init())
  }

  public func listEndpoints(
    request: ListEndpointsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudIDSV1.ListEndpointsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listEndpoints(
    byItem: ListEndpointsRequest
  ) throws -> any AsyncSequence<Endpoint, Swift.Error> {
    try self.listEndpoints(byItem: byItem, options: .init())
  }

  public func listEndpoints(
    byItem: ListEndpointsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Endpoint, Swift.Error> {
    let listRpc = { (token: Swift.String) async throws -> GoogleCloudIDSV1.ListEndpointsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listEndpoints(
    parent: Swift.String,
  ) throws -> any AsyncSequence<Endpoint, Swift.Error> {
    let request = ListEndpointsRequest().with {
      $0.parent = parent
    }
    return try self.listEndpoints(byItem: request)
  }

  public func getEndpoint(request: GetEndpointRequest) async throws -> GoogleCloudIDSV1.Endpoint {
    try await self.getEndpoint(request: request, options: .init())
  }

  public func getEndpoint(
    request: GetEndpointRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudIDSV1.Endpoint {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getEndpoint(
    name: Swift.String,
  ) async throws -> GoogleCloudIDSV1.Endpoint {
    let request = GetEndpointRequest().with {
      $0.name = name
    }
    return try await self.getEndpoint(request: request)
  }

  public func createEndpoint(request: CreateEndpointRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.createEndpoint(request: request, options: .init())
  }

  public func createEndpoint(
    request: CreateEndpointRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func createEndpoint(withPolling: CreateEndpointRequest) async throws -> any GoogleCloudGax
    .PollableOperation<Endpoint>
  {
    try await self.createEndpoint(withPolling: withPolling, options: .init())
  }

  public func createEndpoint(
    withPolling: CreateEndpointRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Endpoint> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Endpoint>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func createEndpoint(
    parent: Swift.String,
    endpoint: Endpoint?,
    endpointId: Swift.String,
  ) async throws -> any GoogleCloudGax.PollableOperation<Endpoint> {
    let request = CreateEndpointRequest().with {
      $0.parent = parent
      $0.endpoint = endpoint
      $0.endpointId = endpointId
    }
    return try await self.createEndpoint(withPolling: request)
  }

  public func deleteEndpoint(request: DeleteEndpointRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.deleteEndpoint(request: request, options: .init())
  }

  public func deleteEndpoint(
    request: DeleteEndpointRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func deleteEndpoint(withPolling: DeleteEndpointRequest) async throws -> any GoogleCloudGax
    .PollableOperation<Void>
  {
    try await self.deleteEndpoint(withPolling: withPolling, options: .init())
  }

  public func deleteEndpoint(
    withPolling: DeleteEndpointRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Void> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Void>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func deleteEndpoint(
    name: Swift.String,
  ) async throws -> any GoogleCloudGax.PollableOperation<Void> {
    let request = DeleteEndpointRequest().with {
      $0.name = name
    }
    return try await self.deleteEndpoint(withPolling: request)
  }

  public func listOperations(request: GoogleLongRunning.ListOperationsRequest) async throws
    -> GoogleLongRunning.ListOperationsResponse
  {
    try await self.listOperations(request: request, options: .init())
  }

  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listOperations(
    byItem: GoogleLongRunning.ListOperationsRequest
  ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    try self.listOperations(byItem: byItem, options: .init())
  }

  public func listOperations(
    byItem: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleLongRunning.ListOperationsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listOperations(
    name: Swift.String,
    filter: Swift.String,
  ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    let request = GoogleLongRunning.ListOperationsRequest().with {
      $0.name = name
      $0.filter = filter
    }
    return try self.listOperations(byItem: request)
  }

  public func getOperation(request: GoogleLongRunning.GetOperationRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.getOperation(request: request, options: .init())
  }

  public func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getOperation(
    name: Swift.String,
  ) async throws -> GoogleLongRunning.Operation {
    let request = GoogleLongRunning.GetOperationRequest().with {
      $0.name = name
    }
    return try await self.getOperation(request: request)
  }

  public func deleteOperation(request: GoogleLongRunning.DeleteOperationRequest) async throws {
    try await self.deleteOperation(request: request, options: .init())
  }

  public func deleteOperation(
    request: GoogleLongRunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func deleteOperation(
    name: Swift.String,
  ) async throws {
    let request = GoogleLongRunning.DeleteOperationRequest().with {
      $0.name = name
    }
    try await self.deleteOperation(request: request)
  }

  public func cancelOperation(request: GoogleLongRunning.CancelOperationRequest) async throws {
    try await self.cancelOperation(request: request, options: .init())
  }

  public func cancelOperation(
    request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func cancelOperation(
    name: Swift.String,
  ) async throws {
    let request = GoogleLongRunning.CancelOperationRequest().with {
      $0.name = name
    }
    try await self.cancelOperation(request: request)
  }
}
